### ISSUE TITLE
Negative Reputation Stuff?

### ISSUE THREAD

**Issue by Archnitest** [hangilk/TextAdventure#2]
I was thinking that it would be better for our game if we had a -100 to 100 range in terms of reputation where 0 is the neutral value. It would make more sense with negative meaning animosity and positive meaning favorability.

This wouldn't be too hard for me to implement if you guys wish for that. I think the only thing we would consider is how to implement the actual bars. We could have the current system but start in the middle or we could simply have a check that reverses bar movement when in negatives.

**Comment by 82hk** [comment]
Implemented (will be in future commits)
