### ISSUE TITLE
Making Button Options Easier to Use?

### ISSUE THREAD

**Issue by Archnitest** [hangilk/TextAdventure#3]
When  I was working on creating a situation, I realized that the getOptions() method is very bad to use when you have multiple conditionals for the options. The manipulation of the String[] may not result in proper function.

Let's say you remove something from an existing String[]. Do the buttons still function properly or would a blank/null button be formed?

If that is the case, what about having mutually exclusive options which increase your actual options count to >6? Would that experience a run-time error or a logic error, removing the 7+th buttons?

My current idea is to instead of using a String[], we use a Arraylist<String>.

**Comment by 82hk** [comment]
Using ArrayList syntax gets messy really fast, so I'll just implement code that skips over null entries in the String[] entirely, so they don't get displayed in the first place.
