### ISSUE TITLE
Restart Bug

### ISSUE THREAD

**Issue by Archnitest** [hangilk/TextAdventure#5]
I just realized that when an ending is reached and we "restart the game" from the beginning, we simply just set the situation back to the starting one. We don't revert any information. Although I have a method in World.java to reset certain values, it isn't implemented at all. Also, all NPC and location information (most importantly relationship) isn't reset.

**Comment by MiddlePedal** [comment]
I'll take care of that today, although we'll have to go back once all quests are added to make sure every one gets reset.

**Comment by MiddlePedal** [comment]
World.java reset now implemented. Also ty Dean for cleaning up the method.

Everything should work properly now.
